### PR TITLE
studentListing bug (student not found)  resolved

### PR DESCRIPTION
**Pull request by krish-0510**
the student Listing page showed "Student not found" this was because of res.data.students was falsely passed to the useEffect hook, the res to send was res.data.allUser

### CODE REVIEW

**Comment by krish-0510** [comment]
thank you 
your appreciation is much appreciated

**Comment by Manush-2005** [comment]
Wow these are the best 2 lines of code change I will ever seen

**Comment by Manush-2005** [comment]
I am impressed btw

**Comment by krish-0510** [comment]
thanks

**Pull request closed without merging**
